version: "3.7"

services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
      interval: 10s
      timeout: 3s
      retries: 5

  migrate:
    image: migrate/migrate
    env_file: .env
    networks:
      - default
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./migration:/migration
    command: [ "-path", "/migration", "-database",  "postgres://$POSTGRES_DB:$POSTGRES_PASSWORD@database:5432/$POSTGRES_USER?sslmode=disable", "up" ]

  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - default
    ports:
      - "8080:8080"
